import { TooltipProvider } from "@/components/ui/tooltip";
import "../../styles/globals.css";
import { Input } from "@/components/ui/input";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-background w-full h-screen flex items-center justify-center px-4">
          <TooltipProvider>{children}</TooltipProvider>
          <Toaster />
        </main>
      </body>
    </html>
  );
}

