import type { Metadata } from "next";
import "../../styles/globals.css";
import Header from "./Header";
import { TooltipProvider } from "@/components/ui/tooltip";
import ResponsiveContainer from "./ResponsiveContainer";
import {
  Card,
} from "@/components/ui/card";
import Sidebar from "./Sidebar";
import Grid from "../../components/grid/Grid";
import GridItem from "../../components/grid/GridItem";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ResponsiveContainer>
          <Grid cols={4} gap={4} className="pt-4 px-4">
            <GridItem colSpan={1}>
              <Sidebar />
            </GridItem>
            <GridItem colSpan={2}>
              <main className="min-h-[calc(100vh-5rem)] border rounded-t-xl">
                <TooltipProvider>{children}</TooltipProvider>
              </main>
            </GridItem>
            <GridItem colSpan={1}>
              <aside>
                <Card className="min-h-72"></Card>
              </aside>
            </GridItem>
          </Grid>
        </ResponsiveContainer>
      </body>
    </html>
  );
}
